name: class_a_ec
description: "A new Flutter application for ERPCloudSystems."


version: 1.0.15+19

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
    
  # Design
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  another_flutter_splash_screen: ^1.2.1
  flutter_gutter: ^2.2.0
  lottie: ^2.2.0
  animated_text_kit: ^4.2.2
  curved_navigation_bar: ^1.0.6
  flutter_staggered_animations: ^1.1.1
  skeletonizer: ^1.4.2 # Loading Package
  flutter_smart_dialog: ^4.9.8+5
  percent_indicator: ^4.2.4
  cool_alert: ^2.0.1
  loading_indicator: ^3.1.1
  flutter_svg: ^2.1.0
  carousel_slider: ^5.0.0

  
  # Helpers
  equatable: ^2.0.5
  flutter_screenutil: ^5.9.3
  go_router: ^14.6.0
  image_picker: ^1.1.2
  mocktail: ^1.0.4
  shared_preferences: ^2.3.3
  dartz: ^0.10.1
  url_launcher: ^6.3.1
  open_filex: ^4.7.0
  change_app_package_name: ^1.4.0
  flutter_secure_storage: ^9.2.4
  easy_debounce: ^2.0.3
  flutter_widget_from_html: ^0.16.0
  path_provider: ^2.1.5
  file_picker: ^9.0.2
  upgrader: ^11.3.1


  # Notification
  flutter_local_notifications: ^18.0.1

  # Firebase
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.0
  
  # Network
  intl: ^0.20.0
  internet_connection_checker_plus: ^2.5.2
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  pretty_dio_logger: ^1.4.0
  dio: ^5.7.0
  cached_network_image: ^3.4.1


  # State-Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner:
  custom_lint:
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/classA_logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/classA_logo.png"

flutter:

  uses-material-design: true

  assets:
     - assets/fonts/
     - assets/images/
     - assets/lottie/
     - assets/icons/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans_Condensed-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans_Condensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans_Condensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans_Condensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans_Condensed-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 800


dependency_overrides:
  flare_flutter:
    git:
      url: https://github.com/mbfakourii/Flare-Flutter.git
      path: flare_flutter
      ref: remove_hashValues