// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6gbovsGvt8DWcyOG3QM5A3YSXzQS9N-s',
    appId: '1:1064347856669:web:b869ade045fcb6bd97fbf4',
    messagingSenderId: '1064347856669',
    projectId: 'ecs-eb1bc',
    authDomain: 'ecs-eb1bc.firebaseapp.com',
    storageBucket: 'ecs-eb1bc.firebasestorage.app',
    measurementId: 'G-H6NK4833MG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlVSjB3xYHd_5NxZf2AMyycAazV8OZoiI',
    appId: '1:1064347856669:android:150bf9421bc5ac7c97fbf4',
    messagingSenderId: '1064347856669',
    projectId: 'ecs-eb1bc',
    storageBucket: 'ecs-eb1bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbLdL4EDWX1SHW8F_ov4Qtz7US1lm1pjg',
    appId: '1:1064347856669:ios:00a2b2097f8685ad97fbf4',
    messagingSenderId: '1064347856669',
    projectId: 'ecs-eb1bc',
    storageBucket: 'ecs-eb1bc.firebasestorage.app',
    iosBundleId: 'com.erpcloud.systems',
  );

}